### PR TITLE
Small threaded entity tracking improvement

### PR DESCRIPTION
**Pull request by ishland**
This PR does the following things: 
- Make a dedicated thread pool for entity tracking
- Process sync tasks while waiting for tracker to save server thread time

### CODE REVIEW

**Comment by PaulBGD** [comment]
The only way I'd accept a fully parallel entity tracker is if the entire tracking code was rewritten. As it is now, there's too many spots that could cause issues running it completely parallel. I also don't think the gain is that big, the advantage of using `parallelStream` like I was is that it will run it all on the main thread if needed, and only run in the fork pool if there's a lot of tasks. This makes it very easy to enable regardless of how many entities are being tracker.

**Comment by ishland** [comment]
I removed fully parallel entity tracker now.

**Comment by PaulBGD** [comment]
What's the reasoning behind this PR now? It seems to make a lot of allocations (lamdas & futures) without making any improvement to the original code. As well, the entities array shouldn't need to be cloned anymore either.

**Comment by PaulBGD** [comment]
I decided to make a similar change myself that uses the pool directly, to remove the overhead of using the streams: https://github.com/Technove/Airplane/commit/0ddd3fba349d249b25479620caf18409c9a8ce90

Would love your opinion on it (preferably over Discord), but I'm going to close the PR.

**Pull request closed without merging**
